#bash run_joint_lora_moe_training.sh llama 24

bash run_eval_joint_culturemoe.sh root/autodl-fs/joint_lora_moe/llama_CulturalBench_cultureLLM_sharedtrue_gatetrue_masktrue_20260102_215142 llama 0
bash run_eval_joint_culturemoe.sh root/autodl-fs/joint_lora_moe/llama_CulturalBench_cultureLLM_sharedtrue_gatetrue_masktrue_20260102_215142 llama 0 true true false
bash run_eval_joint_culturemoe.sh root/autodl-fs/joint_lora_moe/llama_CulturalBench_cultureLLM_sharedtrue_gatetrue_masktrue_20260102_215142 llama 0 true false
bash run_eval_joint_culturemoe.sh root/autodl-fs/joint_lora_moe/llama_CulturalBench_cultureLLM_sharedtrue_gatetrue_masktrue_20260102_215142 llama 0 false

shutdown