### model
model_name_or_path: output/llama3.1_lora_sft
adapter_name_or_path: saves/llama3.1-8b/lora/sft
trust_remote_code: true

### method
finetuning_type: lora

### dataset
eval_dataset: CulturalBench-Hard_test
task: ceval_validation  # choices: [mmlu_test, ceval_validation, cmmlu_test]
template: fewshot
lang: en
n_shot: 5

### output
# save_dir: saves/llama3.1-8b/lora/eval

### eval
batch_size: 4
