### model
model_name_or_path: /root/autodl-tmp/CultureMoE/Culture_Alignment/Meta-Llama-3.1-8B-Instruct
trust_remote_code: true
use_custom_llama: true  # 新增的参数

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
#lora_target: llama_model #"attention, ffn"  #q_proj, k_proj, v_proj, o_proj #all
lora_target:
  - embed_tokens  # 对 embed_tokens 层应用 LoRA
  - layers.*.self_attn.q_proj  # 对每个 decoder 层的 self_attn.q_proj 应用 LoRA
  - layers.*.self_attn.k_proj  # 对每个 decoder 层的 self_attn.k_proj 应用 LoRA
  - layers.*.self_attn.v_proj  # 对每个 decoder 层的 self_attn.v_proj 应用 LoRA

### dataset
dataset: normad_ed # CulturalBench-Hard_train
template: llama3
cutoff_len: 2048
max_samples: 1000000000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: /root/autodl-fs/saves/llama3.1-8b/lora/sft
logging_steps: 10
save_steps: 1500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# eval_dataset: CulturalBench-Hard_test
# # val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
